In [1]:
import numpy as np

# Creating Numpy array

In [2]:
a = np.array([1,2,3])
print(a.dtype)

int64


In [3]:
a1=np.array([1,2,3],dtype='int8')
print(a1.dtype)

int8


In [5]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)
a2.ndim

[[1 2 3]
 [4 5 6]]
(2, 3)


2

In [6]:
a1=np.arange(100,200,2)
print(a1)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


In [7]:
a3=np.linspace(0,10,num=4)
print(a3)

[ 0.          3.33333333  6.66666667 10.        ]


In [8]:
a4=np.random.rand(2,2)
print(a4)

[[0.8236546  0.02201723]
 [0.21267868 0.05823973]]


In [13]:
a5=np.ones((4,2))
print(a5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
a7=np.identity(3)
print(a7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a6=np.eye(3,5)
print(a6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Indexing a Numpy Array

In [16]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,3])
arr

9


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,9]]])
print(arr[1,1,1])
arr

9


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 9]]])

#Reshaping the Numpy Array

In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,4)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [24]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [27]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
h1=np.array([1,2,3])
h2=np.array([4,5,6])
np.hstack([h1,h2,h1,h2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [29]:
a=np.array([[1,2],[3,4]])
print(a)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


#Sorting and Searching Numpy Array

In [30]:
arr=np.array([3,2,0,1])
arr1=np.array(['banana','apple','cherry'])
arr2=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))
print(np.sort(arr1))
print(np.sort(arr2))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


In [31]:
b=np.array([12,90,380,12,211])
print(np.where(b>12))
print(np.where(b==12))
print(np.where(b%2==0))

c=np.array([[20,24],[21,23],[2,25]])
print(c)
print(np.where(c>21))

(array([1, 2, 4]),)
(array([0, 3]),)
(array([0, 1, 2, 3]),)
[[20 24]
 [21 23]
 [ 2 25]]
(array([0, 1, 2]), array([1, 1, 1]))


#Operations on Numpy Array

In [32]:
l1=[1,2,3]
l2=[4,5,6]
print(l1*l2)

TypeError: can't multiply sequence by non-int of type 'list'

In [33]:
npa1=np.array([1,2,3])
npa2=np.array([4,5,6])
print(npa1*npa2)

[ 4 10 18]


In [34]:
np.cos(npa1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [36]:
a=np.array([1,2,3])
b=a
b[0]=111
print(a)

[111   2   3]


In [37]:
a=np.array([1,2,3])
b=a.copy()
b[0]=111
print(a)

[1 2 3]


In [41]:
npa1=np.array([[1,1,1],[1,1,1]])
npa2=np.array([[2,2,2],[2,2,2],[2,2,2]])
np.matuml(npa1,npa2)

AttributeError: module 'numpy' has no attribute 'matuml'